#!/bin/sh
# 获取提交信息文件路径
COMMIT_MSG_FILE=$1

# 获取提交类型（例如 commit、merge、squash 等）
COMMIT_SOURCE=$2

# 获取当前分支名
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# 获取版本号
VERSION=$(date '+%Y%m%d')

# 定义模板内容
TEMPLATE="[Bug] 
[INTERNAL]
[NBF]

Cause: None
Solution: None
Fixed Version: $VERSION
Branch: $BRANCH"

# 如果提交信息文件为空（例如用户直接运行 `git commit`），插入模板
if [ -z "$(cat "$COMMIT_MSG_FILE")" ] && [ "$COMMIT_SOURCE" != "message" ]; then
  echo "$TEMPLATE" > "$COMMIT_MSG_FILE"
fi