#!/bin/sh
echo "Running prepare-commit-msg hook..."
echo "Commit message file: $1"
echo "Commit source: $2"

# 获取当前分支名
BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "Branch: $BRANCH"

# 获取版本号
VERSION=$(date '+%Y%m%d')
echo "Version: $VERSION"

# 定义模板内容
TEMPLATE="[Bug] 
[INTERNAL]
[NBF]

Cause: None
Solution: None
Fixed Version: $VERSION
Branch: $BRANCH"

# 检查提交信息文件是否为空
if [ -z "$(cat "$1")" ] && [ "$2" != "message" ]; then
  echo "Inserting template..."
  echo "$TEMPLATE" > "$1"
else
  echo "Skipping template insertion."
fi